### ISSUE TITLE
Error importing USFM

### ISSUE THREAD

**Issue by deferredreward** [JEdward7777/codex-wordmap#1]
In Windows 11, the project doesn't seem to be working right. When I setup the project initially I imported the whole ULT and had each book as a codex. I removed many of them to trim things down. But then when trying to 'Import USFM' I get an error:
![Screenshot 2024-08-27 094818](https://github.com/user-attachments/assets/4370758a-09af-408e-a47f-0356416c0981) Note there are some other errors pictured here.

I have also tried connecting a source usfm, it seems to do nothing, but my Psalms codex is enormous.

Including this in case the source text missing means anything. 
![Screenshot 2024-08-26 194109](https://github.com/user-attachments/assets/3094f8b6-e17d-470e-a97b-0fc739215a51)

If I click on source it says no references found.
![image](https://github.com/user-attachments/assets/abc6b021-85e4-421b-b1d2-8130d7a0cf12)

**Comment by JEdward7777** [comment]
I was able to reproduce this issue when running in windows and I believe it is now corrected.  `fd5ab9b69e411fda90747f5c6ea67bd6bdf99649` Please update your extension and see if it works now.

The No references found, is a separate problem, the codex-wordmap plugin only contributes the Wordmap action.
