### ISSUE TITLE
Hebrew is RtL

### ISSUE THREAD

**Issue by deferredreward** [JEdward7777/codex-wordmap#3]
![image](https://github.com/user-attachments/assets/4eec6497-43f0-42d0-9726-3cd07598a6ee)

**Comment by JEdward7777** [comment]
How do you know there is more Hebrew to see?

**Comment by JEdward7777** [comment]
@deferredreward Closing this issue as I believe you communicated to me that it was a misunderstanding.  If there is still something else to be fixed, please open a new issue.
