### ISSUE TITLE
multiple words never deselect

### ISSUE THREAD

**Issue by deferredreward** [JEdward7777/codex-wordmap#4]
When selecting multiple words from the bank they never deselect and continually go to the latest word you align to (getting larger as you add words).

https://github.com/user-attachments/assets/59a1665d-6325-4772-a4f1-aa74b92911b8

**Comment by JEdward7777** [comment]
This issue has been replicated.  Frankly I didn't know that you could select multiple source words, so this feature was never exercised.  Until this is corrected please just drag one word at a time.
